### ISSUE TITLE
[Bug] Lora that breaks the display of other Lora in folders

### ISSUE THREAD

**Issue by klintan96** [zixaphir/Stable-Diffusion-Webui-Civitai-Helper#10]
## Describe Issue
Lora that breaks the display of other Lora in folders

If the problematic Lora is in folder 1, some or all of the Lora in folder 2 will disappear, but if you move the Lora from 2 to 1 or to the main Lora folder, it will reappear.

This problem occurred in the latest update of the Civitai Helper, when it started to create a JSON file for each Lora.

The problem turned out to be in the json file, specifically in the description section.

"description": "Train LoRa is time and resource expensive, you can support my future works here:\u2764\ufe0fBoosty Donation linkAstarotte no omocha!\u00a0\u00a0\u00a0\u00a0<LINK>\u00a0\u00a0\u00a0\u00a0 \u00a0\u00a0<LINK> \u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0<LINK> \u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0<LINK> \u00a0\u00a0\u00a0\u00a0\u00a0\u00a0<LINK>\n\n\n\n\u00a0\u00a0\u00a0\u00a0<LINK>\u00a0\u00a0\u00a0\u00a0 \u00a0\u00a0<LINK> \u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0<LINK> \u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0<LINK> \u00a0\u00a0\u00a0\u00a0\u00a0\n\n\n\n\u00a0\u00a0\u00a0\u00a0<LINK>\u00a0\u00a0\u00a0\u00a0 \u00a0\u00a0<LINK> \u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0<LINK> \u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0<LINK> \u00a0\u00a0\u00a0\u00a0\u00a0\u00a0<LINK>\n\n\n\n\u00a0\u00a0\u00a0\u00a0<LINK>\u00a0\u00a0\u00a0\u00a0 \u00a0\u00a0<LINK> \u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0<LINK> \u00a0\u00a0\u00a0\u00a0\u00a0\n\n\n\n\u00a0\u00a0\u00a0\u00a0<LINK>\u00a0\u00a0\u00a0\u00a0 \u00a0\u00a0<LINK> \u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0<LINK> \u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0<LINK> \u00a0\u00a0\u00a0\u00a0\n\n\n\n\u00a0\u00a0\u00a0\u00a0<LINK>\u00a0\u00a0\u00a0\u00a0 \u00a0\u00a0<LINK> \u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0<LINK> \u00a0\u00a0\u00a0\u00a0\n\n\n\n\u00a0\u00a0\u00a0\u00a0<LINK>\u00a0\u00a0\u00a0\u00a0 \u00a0\u00a0<LINK> \u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0<LINK> \u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0<LINK> \u00a0\u00a0\u00a0\u00a0\n\n\n\n\n\nResize, rename to usable format(<title>_<trigger word>), compile to one civit page, and made this page look fine.\n\nIt's same as old one, but much less size with little lost in quality(yes older is seems little better in details, but not so much).\n\n\n\n\n\n",

**Here is a link to Lora, all Lora from this page have this problem due to the same description.**

https://civitai.com/models/63708?modelVersionId=68326

## Screenshot for UI issue
**If I remove the descriptions from the problematic Lora json file, all Lora work fine.**

![1](https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper/assets/114187408/660581a9-127d-47a3-9680-95d280f3e699)
![2](https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper/assets/114187408/a1c27151-ae2a-4785-82de-8c991e9b2e19)

**Comment by zixaphir** [comment]
For the time being, this can be worked around by disabling the `Show description on card` option in `Settings -> Extra Networks -> [ ] Show description on card`.

**Comment by aylz10** [comment]
这是因为在description中出现了“<“和”>“符号，可以使用re函数将description中可能出现的“<“和”>“符号去除，像这样：
model_info["description"] = re.sub(r'[<>]', "", model_info["description"])

**Comment by zixaphir** [comment]
> 这是因为在description中出现了“<“和”>“符号，可以使用re函数将description中可能出现的“<“和”>“符号去除，像这样： model_info["description"] = re.sub(r'[<>]', "", model_info["description"])

Unfortunately, this creates other issues for me: What if the user wants to keep `<>` characters in the model description? 

The author of webui and I disagree on the feature of supporting HTML in the model description, so I'll be trying to work on a solution that will allow `<>` characters without triggering the HTML parser.

---
当然可以！以下是这段英文文本的简化中文翻译，同时附上翻译由ChatGPT生成的声明：

"不幸的是，这对我而言带来了其他问题：如果用户想在模型描述中保留 <> 字符怎么办？

WebUI的作者和我在支持模型描述中的HTML功能方面存在分歧，因此我将尝试制定一个解决方案，允许 <> 字符而不触发HTML解析器。"

翻译提示：此翻译由ChatGPT生成。

**Comment by aylz10** [comment]
> > 这是因为在description中出现了“<“和”>“符号，可以使用re函数将description中可能出现的“<“和”>“符号去除，像这样： model_info["description"] = re.sub(r'[<>]', "", model_info["description"])
> 
> Unfortunately, this creates other issues for me: What if the user wants to keep `<>` characters in the model description?
> 
> The author of webui and I disagree on the feature of supporting HTML in the model description, so I'll be trying to work on a solution that will allow `<>` characters without triggering the HTML parser.
> 
> 不幸的是，这对我而言带来了其他问题：如果用户想在模型描述中保留 <> 字符怎么办？
> 
> WebUI的作者和我在支持模型描述中的HTML功能方面存在分歧，因此我将尝试制定一个解决方案，允许 <> 字符而不触发HTML解析器。
> 
> 翻译提示：此翻译由ChatGPT生成。

的确，我没有想到这个情况，或许可以使用转义字符 
  "&lt;"来替换"<"，"&gt;"来替换">"

**Comment by zixaphir** [comment]
I've taken some steps to prevent this from happening in the future, but current files will need to be rescanned with "Replace Old Metadata Formats" enabled.
