### ISSUE TITLE
Extra Networks Directory update breaks UI elements

### ISSUE THREAD

**Issue by Foolishkun** [zixaphir/Stable-Diffusion-Webui-Civitai-Helper#108]
## Have you read document?
Issue is not yet addressed.

## Have you checked console log window's msg?
No relevant console messages.

## Describe Issue
Lower model card icons not showing with [Sj-Si](https://github.com/Sj-Si) new Extra Networks Directory update

https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/15530
https://github.com/Sj-Si/stable-diffusion-webui/tree/extra-networks-performance-updates

https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/15530#issuecomment-2133967172
"I changed quite a bit of the HTML layout for this update so a lot of the class names have changed."

## Screenshot for UI issue
<img width="209" alt="chrome_wJ5f6NkfVv" src="https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper/assets/78248478/8b1f2a8f-4005-47c5-ac47-d80cab69899b">

**Comment by Sj-Si** [comment]
My PR is still a draft so things may continue to change. I wouldn't put in an issue here until that PR gets landed in the dev branch.
