### ISSUE TITLE
Batch Download error

### ISSUE THREAD

**Issue by rugafo** [zixaphir/Stable-Diffusion-Webui-Civitai-Helper#109]
Batch Download error
use civital helper v1.8.8
error code
"
An error has occurred while downloading: 'type'
('type',)
"

use opsion parameters: ::AllFiles
I was able to download the .safetensors but no preview was generated.

I also get the following error
"
An error has occurred while downloading: Invalid URL 'skip': No scheme supplied. Perhaps you meant https://skip?
("Invalid URL 'skip': No scheme supplied. Perhaps you meant https://skip?",)
"

**Comment by zixaphir** [comment]
Can you post the URL you tried to download?

**Comment by rugafo** [comment]
https://civitai.com/models/484130/pony-xl-candice-pokemon?modelVersionId=538427
The above is just one example, but the error will occur in all models.

**Comment by zixaphir** [comment]
Alright, should be fixed now https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper/commit/0b0bc736b05065dfe1c2266add1f63a7e26d3736

**Comment by rugafo** [comment]
thx
