### ISSUE TITLE
NSFW filter isn't working 

### ISSUE THREAD

**Issue by angelika3377** [zixaphir/Stable-Diffusion-Webui-Civitai-Helper#110]
The extension downloads porn (nsfw images) after scanning and pressing Update image generation information (Experimental).
Please fix this, this is horrible :(

**Comment by zixaphir** [comment]
I apologize for this issue. Nobody who wants to avoid this kind of content should have to see it, and I'm sorry that has been your experience. This was a lack of foresight on my part while merging in code from others. I should have accounted for this while reviewing the code. It should be fixed now.

**Comment by angelika3377** [comment]
now there is no button to update image generation information at all :(

**Comment by zixaphir** [comment]
> now there is no button to update image generation information at all :(

It didn't actually work. It had been broken for awhile, since Civitai switched to JPEG images, which don't have the same metadata PNGs do.

**Comment by DEAD1SIDE** [comment]
> > now there is no button to update image generation information at all :(
> 
> It didn't actually work. It had been broken for awhile, since Civitai switched to JPEG images, which don't have the same metadata PNGs do.

So it cant update the images on the models?
