### ISSUE TITLE
How to turn off new "Helper Browser" tab, it's clutter

### ISSUE THREAD

**Issue by ewebgh33** [zixaphir/Stable-Diffusion-Webui-Civitai-Helper#119]
## Have you read document?
Yes

## Have you checked console log window's msg?
Yes

## Describe Issue
Updated the extension and got a new tab that I don't want / need. I want to disable the tab called "Civitai Helper Browser"
Who asked for this?
Why do I want this in Auto1111 instead of just opening a new tab and going to the CivitAI site myself?

**Can I have an option to turn this tab OFF please? It's adding clutter and messing up the tabs I use most.**

## Screenshot for UI issue
N/A

## Console log's msg or screenshot for function issue
N/A

**Comment by zixaphir** [comment]
I'll get to this when I can. I apologize that this feature is unwanted.

**Comment by ewebgh33** [comment]
Thanks
I am sure people will use it, personally I will not so an option to turn it off would be appreciated, thank you
Don't mind if the default is to have it on, again just personally, being able to have the option is good
