### ISSUE TITLE
JSON file with long garbage in description field is created for each checkpoint (instead notes field)

### ISSUE THREAD

**Issue by ostap667inbox** [zixaphir/Stable-Diffusion-Webui-Civitai-Helper#122]
I previously used this version: https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper
There's a problem there now: the Civitai Helper buttons have disappeared on the checkpoint tiles.
I installed this version and ran into another problem:

When scanning for each checkpoint, a JSON file is created and a long unnecessary description of the model is written to the **description** field. Like this: [ac_neg1.json](https://github.com/user-attachments/files/16439592/ac_neg1.json):
Now every tile has this longest ugly useless glitchy text:
![garbage-json](https://github.com/user-attachments/assets/16780eb7-1f9e-4227-919b-70cd7c2a5bd5)

Why? Who needs it here?
If I need to see useful information on the checkpoint tile, such as recommended settings, I open the WebUI metadata editor and add it to the description field myself.  That's what the description field is for:
![good-json](https://github.com/user-attachments/assets/6837ea55-3ff3-48a3-9663-cfa3b0de656e)

And long chatter-laden texts from checkpoint authors that are useless for work are not needed there! You can't even read them, because they don't fit on the checkpoint tile.

**There is a 'notes' field in the json file that is more suitable for this purpose.** It is not visible on the checkpoint tile, but it is in the description of the checkpoint when we open its properties in WebUI metadata editor. How about filling the NOTES field instead of DESCRIPTION when the "Also add data for WebUI metadata editor" checkbox is enabled in the plugin settings?

**Comment by zixaphir** [comment]
This will not be changed. I have done it this way for as long as I have maintained this version, and I have maintained this version for as long as there's been a maintained version compatible with the version of WebUI that introduced the metadata editor. The Description as it is used in this version is for displaying the model description, and the Notes field is used for displaying the Model Version Description.
