### ISSUE TITLE
Rating LoRas?

### ISSUE THREAD

**Issue by paboum** [zixaphir/Stable-Diffusion-Webui-Civitai-Helper#132]
Hello again. I'm using lots of LoRas, some all well trained and useful, others disrupt the scene or simply break it.

I would like Model Cards to include the following:
- Cards could be larger by default, e.g 512x512 px (size configurable via settings)
- The SD1.5/SDXL/Flux/other type of model icon if detected (and preferably possible for the user to modify it) - AFAIU, this is already used for filtering additional models relevant to the selected checkpoint
- The model's author (again, could be disabled in settings)
- Model rating, e.g. from 1 to 5 stars, easily editable via click on model card, possible to disable in settings
- Release date of the file (again, omittable via settings, probably disabled by default)
- Filtering and sorting with the new fields

Since the feature seems rather large and I know some python, you may just start with pointing out which files you expect to be modified, describe architectural limitations (what, if anything, is not feasible to do), PR acceptance criteria (or other contribution guidelines) and I'll give a try implementing it myself.

**Comment by zixaphir** [comment]
I would avoid touching anything until Webui gets it's Extra Networks UI update. This extension isn't actually responsible for most of the user interface, it just populates the existing UI.

https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/15530

**Comment by paboum** [comment]
Okay then, I'll track that other ticket then. Thx
