### ISSUE TITLE
[Feature]为是否生成.json文件添加开关

### ISSUE THREAD

**Issue by aylz10** [zixaphir/Stable-Diffusion-Webui-Civitai-Helper#14]
可否为是否生成.json文件添加控制开关
我修改了sd-webui的modules\extra_networks.py使其可以直接读取civitai.info文件的元数据，当我需要更改模型信息、描述内容、自动选择vae等信息时，直接保存为json文件的数据，并且可以直接在文件夹中看有没有json文件可以很直观的判断出哪些是自己修改了内容，哪些使用的是原始的civitai元数据.如果每个模型都生成civitai.info和.json文件，那么就失去了这个便利的判断方法

**Comment by zixaphir** [comment]
Added in v1.7.3
