### ISSUE TITLE
[Feature]增加civitai元数据示例图图片生成信息功能，并将生成信息按照civitai.info的格式保存到meta中

### ISSUE THREAD

**Issue by aylz10** [zixaphir/Stable-Diffusion-Webui-Civitai-Helper#17]
civitai网站元数据中，有些示例图没有meta信息，
例如这个lora：[Cute01-000002](https://civitai.com/models/99455)的[示例图
](https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/a2fade05-5948-45df-97b8-9f5c03921b2e/width=450/1331406.jpeg)civitai.info中没有meta信息，但是将图片导入png_info中可以读取到图片生成信息
希望可以增加为civitai元数据示例图图片生成信息功能，并将图片生成信息按照civitai.info的格式保存到meta中
思路是：使用requests.get函数获取示例图片数据，然后使用modules.extras.run_pnginfo函数读取图片生成信息，再按照civitai.info中的meta格式保存到civitai.info元数据中

**Comment by zixaphir** [comment]
I think this sounds like a neat idea, but I'd prefer not to implement it. Would you be willing to make a pull request?
我觉得这听起来是个不错的想法，但我宁愿不去实现它。你愿意提交一个拉取请求吗？

**Comment by aylz10** [comment]
我会尝试提交一个pull request。设计一个新按钮，遍寻更新已经下载好的本地civitai.info文件，不影响原有下载功能
