### ISSUE TITLE
[BUG] Model link does not open version just the model main page

### ISSUE THREAD

**Issue by JingJang** [zixaphir/Stable-Diffusion-Webui-Civitai-Helper#33]
Currently it opens the latest model rather than the model version page. Should it should have "?modelVersionId=<id>" in the url.

(Edit: Corrected the mistake)

**Comment by zixaphir** [comment]
I am sorry but the description and title seem in conflict. Is it showing the model version page or just the same model page you'd get when you open a model from Civitai's website? It is meant to open civitai.com/model/[id]

**Comment by JingJang** [comment]
Yeah. It is in conflict. It's the opposite of what I wanted to say. 

For example when I click "Dreamscapes & Dragonfire version DS&Dv1.0_Inpainting" I expect to open that version of the model rather than the main page, which contains the latest version (not always downloaded).

So it should open: 
        https://civitai.com/models/50294?modelVersionId=66510
Instead of
      https://civitai.com/models/50294

**Comment by zixaphir** [comment]
That is the intended behavior.

**Comment by JingJang** [comment]
Fair enough. I thought it would be more sensible to see the version info.
