### ISSUE TITLE
Need an option to use Lora directory for LyCORIS downloads

### ISSUE THREAD

**Issue by Zolxys** [zixaphir/Stable-Diffusion-Webui-Civitai-Helper#35]
Native support for LyCORIS was added to stable-diffusion-webui at v1.5.0 on Jul 25. LyCORIS models are now treated the same as Loras and go in the Lora directory. This thing still wants to download them to models/LyCORIS which doesn't exist, so it fails.

This either needs to:
A) Provide an option to use the Lora directory for LyCORIS downloads.
or
B) Automatically use the Lora directory in v1.5.0 and above.

**Comment by zixaphir** [comment]
The LyCORIS directory is still used and supported by WebUI. I can add a shim to ensure it exists in future versions and fallback to the lora directory, but support for the LyCORIS directory will continue to exist as long as WebUI supports it. Until I write in the code for a fallback directory, you can use the command line option `--lyco-dir-backcompat` to change the LyCORIS directory to point to the Lora directory, I believe.

**Comment by zixaphir** [comment]
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper/commit/807eee63ecea3126cd59d9407362347c89ed1ab0
