### ISSUE TITLE
lora名字太长问题

### ISSUE THREAD

**Issue by chen135347542093** [zixaphir/Stable-Diffusion-Webui-Civitai-Helper#4]
![image](https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper/assets/104272971/9ec7dc6c-9702-415a-a601-3274d73905a8)

**Comment by zixaphir** [comment]
I'm not sure what to do about this. The lora card UI and thus the lora title is managed by webui. This extension doesn't change anything except adding additional buttons.

我不太确定如何处理这个问题。Lora卡片的用户界面以及Lora标题都是由WebUI管理的。这个扩展不会改变任何内容，只是添加了额外的按钮。
（翻译由ChatGPT提供）

**Comment by chen135347542093** [comment]
> 我不知道该怎么办。劳拉卡 UI 和因此的劳拉标题由 webui 管理.此扩展程序除了添加其他按钮外不会更改任何内容。
> 
> 我不太确定如何处理这个问题。Lora卡片的用户界面以及Lora标题都是由WebUI管理的。这个扩展不会改变任何内容，只是添加了额外的按钮。 （翻译由ChatGPT提供）

是否可以通过设置一个不显示lora名称的按钮解决呢

**Comment by ytn2001** [comment]
因为生成了json文件，显示了json的内容

**Comment by zixaphir** [comment]
> 因为生成了json文件，显示了json的内容
The display of the description on the model card is an optional feature of SD WebUI and can be disabled by altering the `Show description on card` option under `Settings -> Extra Networks`

模型卡上的描述显示是 SD WebUI 的可选功能，可以通过更改 `Show description on card` 选项来禁用它，位于 `Settings -> Extra Networks`。
以上内容由ChatGPT翻译
![Screenshot_20230913-024158](https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper/assets/438570/0626eb67-ab6d-4fe2-a8ff-65aa90a1dcb0)
