### ISSUE TITLE
Cannot find the proxy textbox

### ISSUE THREAD

**Issue by ganganray** [zixaphir/Stable-Diffusion-Webui-Civitai-Helper#46]
## Have you read document?
Yes

## Have you checked console log window's msg?
Yes

## Describe Issue
As a user from CN, I need to setup proxy to download from civitai. It is written in the introduction of this project that "Proxy textbox is at the bottom of extension tab". However, I simply cannot find it. I am running the v1.8.0 version of sd_civitai_helper and v1.6.0 of webui

**Comment by zixaphir** [comment]
I apologize, this has been moved into the Settings tab. I'll update the readme soon

**Comment by zixaphir** [comment]
I've updated the README to place the Proxy section under the newly added Settings section
