### ISSUE TITLE
Update Image Generation Information (Experimental)

### ISSUE THREAD

**Issue by Quidam2k** [zixaphir/Stable-Diffusion-Webui-Civitai-Helper#47]
Is there documentation for this feature? I did look, but sometimes I miss what's in front of my face.

**Comment by zixaphir** [comment]
No, sorry. I should have written some when I added it, but this was a feature originally written by a contributor and it slipped my mind. The intention of the feature is to pull missing information about preview images for use with the "use image prompt" button when this information is missing from Civitai's API but exists in the preview image's metadata. If you don't ever use that feature, it's a waste of your time

**Comment by zixaphir** [comment]
I've added a small section to the README covering this
