### ISSUE TITLE
BUG: "Always Display Buttons"

### ISSUE THREAD

**Issue by JingJang** [zixaphir/Stable-Diffusion-Webui-Civitai-Helper#5]
"Always Display Buttons" in the settings menu is not saved. So everytime you restart SD you have to set it again.

**Comment by zixaphir** [comment]
As far as I could gather, webui was storing settings values in the global `ui_config.json` and overwriting the saved settings. Instead of trying to write a workaround for that, from now on the civitai helper settings will just be in the settings tab where all the other extensions' settings live.
