### ISSUE TITLE
Incompatible with SD.Next since 0da8c70

### ISSUE THREAD

**Issue by LaaZa** [zixaphir/Stable-Diffusion-Webui-Civitai-Helper#52]
## Describe Issue
Commit 0da8c70426db008638093e8076ddce7a9ce402aa introduced `modules.cache` import which does not exist in SD.Next.
Instead same functionality is provided by the `hashes` module.
`import modules.hashes as sha256_cache` should fix it, but hashes is already imported anyway.

**Comment by zixaphir** [comment]
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper/commit/ef0465626662fac2e6388cefb6de386aeaa10ba4
