### ISSUE TITLE
Feature Request - Section to add tags to loras

### ISSUE THREAD

**Issue by dthmax** [zixaphir/Stable-Diffusion-Webui-Civitai-Helper#68]
Hello, first of all thanks for this extension is a life saver.

i wanted to ask if it would be possible to add a section in the models, more specifically in Loras, to add Tags to search different models.

I know that you can put the models in different folders but i meant a way to search for different models that share features.

IE: lets say that i have some character loras that i added the tags for series, gender, hair color. 
So when i want test male character loras i only search for that. 
or if i want to search for characters of the same series i can do that too.
same if i add the tag NSFW or SFW.

thanks for your time, and thanks again for the helper!
have a nice 2024!

**Comment by zixaphir** [comment]
Hello! This extension does not implement the Extra Networks UI used by WebUI. The existing Extra Networks UI is from [automatic1111/stable-diffusion-webui](https://github.com/AUTOMATIC1111/stable-diffusion-webui). The existing search functionality is provided entirely within webui: this extension only populates the metadata with compatible data from civitai. If you'd like the search functionality expanded, I'd advise making an issue there.
