### ISSUE TITLE
Why wrap the already-sanitized model HTML in HTML comments?

### ISSUE THREAD

**Issue by mx** [zixaphir/Stable-Diffusion-Webui-Civitai-Helper#78]
The trim_html function in util.py is removing HTML tags that don't match a whitelist. That's great! Following that though, the entire string is wrapped in an HTML comment before being returned. This messes up other extensions that attempt to display the civitai info file (specifically https://github.com/CurtisDS/sd-model-preview-xd, not sure if any others use these civitai info files or not, but that's the one I used where I noticed the problem). Unless there's a particular reason for doing this that I'm missing (which is quite possible!) it feels pretty redundant given that you already removed all non-whitelisted tags.

If my assumption is correct and this is just strictly redundant, could this be removed so that extension works without modification?

**Comment by mx** [comment]
Obviously you'd need to remove line 387 if you were to make this change. The whole thing does feel a bit fragile attempting to parse out tags with regexes instead of cleaning it with BeautifulSoup (for the allowlist) and bleach or html.escape() (for everything else). If you want, I can send a pull request to do that to ensure it's sanitized properly, and remove the comment-wrapping.

**Comment by zixaphir** [comment]
I did look into other options but I was not satisfied with any of them at the time I decided to just comment everything out
