### ISSUE TITLE
Buttons don't show up on lllyasviel's fork

### ISSUE THREAD

**Issue by mohitsrivastavazzz** [zixaphir/Stable-Diffusion-Webui-Civitai-Helper#79]
## Have you read document?
Yes
## Have you checked console log window's msg?
Yes
## Describe Issue
Buttons don't show up on lllyasviel's fork,

**Comment by mohitsrivastavazzz** [comment]
Please consider updating it to work on this forge. I'll even pay if you want.

**Comment by zixaphir** [comment]
I'm closing this because I've been using Illysviel's fork for some time now and this does not appear to be an issue anymore.
