### ISSUE TITLE
[Bug] Webui forge support / Lobe theme infinite loading issue

### ISSUE THREAD

**Issue by CasanovaSan** [zixaphir/Stable-Diffusion-Webui-Civitai-Helper#80]
So i installed this extension on webui [forge](https://github.com/lllyasviel/stable-diffusion-webui-forge), and there are a few features that are missing 
The buttons that appear on the model previews are missing 
![image](https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper/assets/138389174/e0075634-1e52-4959-8748-1a83fc5d06b0)

And there is also another problem and that is when i am using the lobe theme for webui forge or a1111, the extra networks are not loading (this does not happen with the civitai extension opened, i did contact the lobe theme creator but i still did not get a response) 
![image](https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper/assets/138389174/1e1c0d70-20a4-44fd-827b-7678c7ceac82)

**Comment by nicknamerequired** [comment]
I have the same issues. there is no refresh button in the loras and checkpoints.
The list of loras is the same for XL and SD1.5. Before we had a different list for the kind of model loaded.
The textual inversion tab is empty.
It is too bad, forge is faster than regular SD UI and the civitai helper is a great tool.

Forge has been released recently, I understand devs didn't update their tool or maybe it(s not easy to update.

**Comment by mohitsrivastavazzz** [comment]
@CasanovaSan @nicknamerequired 
Hey [this](https://github.com/blue-pen5805/Stable-Diffusion-Webui-Civitai-Helper) fork of civitai helper apparently works with the forge. Just try it

**Comment by nicknamerequired** [comment]
> @CasanovaSan @nicknamerequired Hey [this](https://github.com/blue-pen5805/Stable-Diffusion-Webui-Civitai-Helper) fork of civitai helper apparently works with the forge. Just try it

It works! Thanks a lot!

**Comment by coderCK2** [comment]
> @CasanovaSan @nicknamerequired Hey [this](https://github.com/blue-pen5805/Stable-Diffusion-Webui-Civitai-Helper) fork of civitai helper apparently works with the forge. Just try it

Thank you for this! I came here with the same issue, and the forked version works for me in Forge.

> I'm getting errors even with this fork when I try to 'scan'.
> 
> ` chunk = file.read(size) PermissionError: [Errno 13] Permission denied`

@DrSniffy I did not have this issue, but I also launch Forge/A1111 from an elevated prompt. Give that a try and see if it helps.

**Comment by zixaphir** [comment]
This extension has no known incompatibilities with Forge (which I use as my primary UI). The Lobe theme has not ever been supported by this extension. Any who would like to support the Lobe theme are welcome to send a pull request.
