### ISSUE TITLE
[Bug] - Buttons shows on only 14 model cards while others don't, and when click on buttons, they do nothing

### ISSUE THREAD

**Issue by suonnon** [zixaphir/Stable-Diffusion-Webui-Civitai-Helper#83]
## Have you read document?
Yes

## Have you checked console log window's msg?
Yes, all normal

## Describe Issue
Related to the issue ["Button does not show on model cards - A1111 ver 1.8RC"](https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper/issues/82), the issued was fixed but not completely.
The buttons only shows on my 14 model cards, while other doesn't. And when I click on the buttons, they don't do anything.

And the buttons disappeared after press the "refresh page" button on the A1111 webui.

**Comment by Eversor** [comment]
My buttons (like use prompt from original image) don't show up either since today.

**Comment by zixaphir** [comment]
I apologize. I overlooked double-checking the current stable webui release when updating for the upcoming version. Should be fixed now.
