### ISSUE TITLE
[Bug] - Buttons actions not working

### ISSUE THREAD

**Issue by suonnon** [zixaphir/Stable-Diffusion-Webui-Civitai-Helper#85]
## Have you read document?
Yes

## Have you checked console log window's msg?
Yes,

## Describe Issue
The actions for the buttons does not work. I meant all actions, e.g: open model's URL, add trigger word, use prompt from thumb, rename, delete.

Relate to the issue with latest update of A1111 (version 1.8).

It happen with all of the models. Maybe the extension gets the wrong model's info when scanning the models I guess.

I tried to
- Delete all of the json, info, preview of the models and do the scanning again => The issue still there.
- Delete and reinstall the extension => The issue still there.

## Console log's msg or screenshot for function issue
This is the screenshot as an example:
![image](https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper/assets/133345496/fc8c8bd7-2f24-400f-9f1b-433e50751f7d)

**Comment by zixaphir** [comment]
Sorry, I'm running on Linux and this appears to be an issue affecting Windows. I'm not sure why it's happening *now* when it didn't before, but I'm chasing down where it's happening.

**Comment by zixaphir** [comment]
I'm glad we finally got this resolved
