### ISSUE TITLE
[Bug] Civitai API NSFW Changes

### ISSUE THREAD

**Issue by zixaphir** [zixaphir/Stable-Diffusion-Webui-Civitai-Helper#88]
Currently things are broken and model preview images cannot be downloaded. I'm working in a fix but I wanted to post this in the interim to let people know it will be fixed soon.

**Comment by echdareez** [comment]
Thanks for looking into this and the notification :-) 
Not sure if it's related to this but I was able to 'circumvent' some failing models (from a batch that I downloaded yesterday and with a message about the NSFW level) by moving them temporarily out of the stablediffusion models dir. 
And these were the models : 
aiCREAT0RXLARTISTIC_v40BOLDER.safetensors
halcyonSDXL_v13NSFW.safetensors
rhapsodyxl_v10.safetensors

**Comment by zixaphir** [comment]
> Thanks for looking into this and the notification :-) Not sure if it's related to this but I was able to 'circumvent' some failing models (from a batch that I downloaded yesterday and with a message about the NSFW level) by moving them temporarily out of the stablediffusion models dir. And these were the models : aiCREAT0RXLARTISTIC_v40BOLDER.safetensors halcyonSDXL_v13NSFW.safetensors rhapsodyxl_v10.safetensors

I have implemented the API changes but it's likely that some models on civitai's end will have issues. Do you have the URLs for these models so that I can verify?

**Comment by echdareez** [comment]
Certainly : 
https://civitai.com/models/299933/halcyon-sdxl-photorealism
https://civitai.com/models/123396/rhapsodyxl

For the aiCREAT0R : 
https://civitai.com/models/219616
But I was using the "v4.0 BOLDER" version and the author of that mod has released a new version yesterday... So not sure how his "v5.0 Art_Lover" will behave (as I haven't downloaded it yet)

**Comment by zixaphir** [comment]
So far no issues with the new NSFW categories when scanning those, but I am finding new issues with civitai's API. Not sure how to address them right now, but it appears only the most recent version of a model is accessible. I'm not sure if this is a bug or if Civitai is introducing a new endpoint to fetch the other versions.

**Comment by echdareez** [comment]
No worries and thanks for looking :-)  
As for those API changes, I noticed this behaviour/bug with another extension : 
https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper/issues/89
So it is indeed so that only the most recent version is accessible/visible.

**Comment by zixaphir** [comment]
I'm closing this issue because the NSFW categories have been updated in the code and the newer issues with Civitai's API has its own issue.
