### ISSUE TITLE
[Feature] Store SHA256 instead of nothing when no Civitai link exists

### ISSUE THREAD

**Issue by JingJang** [zixaphir/Stable-Diffusion-Webui-Civitai-Helper#9]
In the info file, if it does not link to Civitai it just stores `{}`. It would be nice to store the SHA256, AutoV2 and maybe original filename of the file in-case person (aka me) renames it. 

Also JSON structure for trigger words, so you can fill it manually yourself.

**Comment by zixaphir** [comment]
The empty file is only really there to tell the extension not to waste time trying to scan the model and ping Civitai's servers uselessly. I suppose adding additional data for advanced users isn't too much to ask. I'll look into working on that.

**Comment by JingJang** [comment]
Relevant thread https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/13152#issuecomment-1712809871

Here is an example of a skeleton info file that I created. This one points to https://huggingface.co/stabilityai/stable-diffusion-2-1

The file size is incorrect.

```{
  "id":,
  "modelId":,
  "name": "Stable-Diffusion-Model",
  "trainedWords": [
    "Missing",
    "Missing"
  ],
  "baseModel": "SD 2.1",
  "description": null,
  "model": {
    "name": "Stable-Diffusion2-1",
    "type": "checkpoint",
    "nsfw": false,
    "poi": false
  },
  "files": [
    {
      "name": "v2-1_768-nonema-pruned.ckpt",
      "sizeKB": 36990.6375,
      "type": "Model",
      "hashes": {
        "AutoV2": "ff144a4984",
        "SHA256": "ff144a49841cf383adbc68841272ce639e1032b0a1f0f6586347feb953c244f4"
      }
    }
  ],
  "downloadUrl": "https://huggingface.co/stabilityai/stable-diffusion-2-1"
}
```

**Comment by zixaphir** [comment]
Likely I'd keep the original structuring, but I don't see any point in storing anything that's a `null` value.

**Comment by JingJang** [comment]
Just an outline for trigger words and what the end user might fill out.
