### ISSUE TITLE
download function niot working 

### ISSUE THREAD

**Issue by Jeffpiatt2k4** [zixaphir/Stable-Diffusion-Webui-Civitai-Helper#90]
## Describe Issue
 I am attempting to download models from Civial and keep getting errors shows as a py crash

Civitai Helper: Getting model info by: https://civitai.com/models/50905/kirari-momobami?modelVersionId=55427
Civitai Helper: Run get_model_id_from_url
Civitai Helper: Request model info from civitai: 50905
Civitai Helper: GET Request failed with error code:
   404: Not Found
Civitai Helper: An error occurred while attempting to process model info:
        'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "D:\sd.webui\system\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\sd.webui\system\python\lib\site-packages\gradio\blocks.py", line 1434, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "D:\sd.webui\system\python\lib\site-packages\gradio\blocks.py", line 1297, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "D:\sd.webui\system\python\lib\site-packages\gradio\blocks.py", line 1272, in validate_outputs
    raise ValueError(
ValueError: An event handler (get_model_info_by_url) didn't receive enough output values (needed: 6, received: 1).
Wanted outputs:
    [state, textbox, textbox, dropdown, dropdown, <gradio.layouts.Column object at 0x000001D080891900>]
Received outputs:
    [None]

**Comment by zixaphir** [comment]
Civitai's API is currently having issues. There's nothing I can do on this end but what for them to fix it. You can follow this issue for the most up-to-date information: https://github.com/civitai/civitai/issues/1100

**Comment by zixaphir** [comment]
Civitai's API seems to be at least giving a response now. Some models still won't work due to https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper/issues/89, but this is also a Civitai API problem that I can't do anything about

**Comment by zixaphir** [comment]
seems to be fixed
